# -*- coding: utf-8 -*-
"""AI-3(selection-sort).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Re5d4kLkEb38VyciVXEvjdP_z98Ajyqb
"""

def selection_sort(arr):
    n = len(arr)

    for i in range(n - 1):
        min_index = i

        # Find the minimum element in the remaining unsorted portion of the array
        for j in range(i + 1, n):
            if arr[j] < arr[min_index]:
                min_index = j

        # Swap the minimum element with the first element of the unsorted portion
        arr[i], arr[min_index] = arr[min_index], arr[i]

    return arr

# Take input array from the user
input_str = input("Enter the elements of the array (space-separated): ")
array = [int(x) for x in input_str.split()]

# Perform selection sort
sorted_array = selection_sort(array)

# Print the sorted array
print("Sorted array:", sorted_array)